repos:
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.1.1
- hooks:
  - id: fmt
  - id: cargo-check
  - id: clippy
  repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
- repo: https://github.com/adamchainz/pre-commit-dprint
  rev: v0.36.0
  hooks:
  -   id: dprint
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.1
  hooks:
    - id: gitleaks
